apiVersion: v1
kind: Service
metadata:
  name: bootstrap-service
spec:
  selector:
    app: bootstrap-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
